#!/bin/bash

function files_that_are_no_reference_in_app(){
    FILES_TO_LOOK=`find ./resources -name '*png' | grep -v 'Default' | grep -v '@2x'`

    for file in $FILES_TO_LOOK
    do
      name=`basename $file`
      if ! grep -qhsr "$name" ./app; then
        echo "$file"
      fi
    done
}


files_that_are_no_reference_in_app
